# 简单存内存；将来可改为从数据库/Blob读取
POI_CATEGORIES = [
    {
        "id": "cycling",
        "label": "Cycling",
        "icon": "cycling",
        "group": "Activities",
        "defaultVisible": True,
    },
    {
        "id": "camping",
        "label": "Camping",
        "icon": "camping",
        "group": "Activities",
        "defaultVisible": True,
    },
    {
        "id": "kayaking",
        "label": "Kayaking",
        "icon": "kayaking",
        "group": "Activities",
        "defaultVisible": True,
    },
    {
        "id": "bird",
        "label": "Birdwatching",
        "icon": "bird",
        "group": "Activities",
        "defaultVisible": True,
    },
    {
        "id": "fishing",
        "label": "Fishing",
        "icon": "fishing",
        "group": "Activities",
        "defaultVisible": True,
    },
    {
        "id": "trailhead",
        "label": "Trailhead",
        "icon": "trailhead",
        "group": "Access & Facilities",
        "defaultVisible": True,
    },
    {
        "id": "parking",
        "label": "Car Park",
        "icon": "parking",
        "group": "Access & Facilities",
        "defaultVisible": True,
    },
    {
        "id": "amenity",
        "label": "Public Amenities",
        "icon": "restroom",
        "group": "Access & Facilities",
        "defaultVisible": False,
    },
]

POIS = [
    {
        "id": "poi-kaituna-cycling",
        "category": "cycling",
        "name": "Kaituna Riverside Ride",
        "description": "Smooth gravel riding beside the Kaituna River with views across Te Waihora.",
        "lat": -43.75,
        "lng": 172.35,
        "image": "https://images.unsplash.com/photo-1508609349937-5ec4ae374ebf?auto=format&fit=crop&w=600&h=400&q=60",
        "gmaps": None,
        "isPublic": True,
    },
    {
        "id": "poi-yarrs-flat-bird",
        "category": "bird",
        "name": "Yarrs Flat Bird Sanctuary",
        "description": "Boardwalk and hides that overlook one of the lake's most active bird rookeries.",
        "lat": -43.79,
        "lng": 172.26,
        "image": "https://images.unsplash.com/photo-1501706362039-c6e80948c98d?auto=format&fit=crop&w=600&h=400&q=60",
        "gmaps": None,
        "isPublic": True,
    },
    {
        "id": "poi-greenpark-camp",
        "category": "camping",
        "name": "Greenpark Sands Camp",
        "description": "Basic lakeside campsite with flat tent sites and access to the shoreline.",
        "lat": -43.78,
        "lng": 172.36,
        "image": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&h=400&q=60",
        "gmaps": "https://www.google.com/maps/dir/?api=1&destination=-43.78,172.36",
        "isPublic": True,
    },
    {
        "id": "poi-harts-fishing",
        "category": "fishing",
        "name": "Harts Creek Fishing Jetty",
        "description": "Popular shore fishing jetty with calm waters and seasonal whitebait runs.",
        "lat": -43.81,
        "lng": 172.44,
        "image": "https://images.unsplash.com/photo-1495105787522-5334e3ffa0ef?auto=format&fit=crop&w=600&h=400&q=60",
        "gmaps": "https://www.google.com/maps/dir/?api=1&destination=-43.81,172.44",
        "isPublic": True,
    },
    {
        "id": "poi-coopers-kayak",
        "category": "kayaking",
        "name": "Coopers Lagoon Kayak Launch",
        "description": "Easy kayak launch with gentle shoreline and sheltered waters for families.",
        "lat": -43.84,
        "lng": 172.52,
        "image": "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&h=400&q=60",
        "gmaps": "https://www.google.com/maps/dir/?api=1&destination=-43.84,172.52",
        "isPublic": True,
    },
    {
        "id": "poi-lakeview-trailhead",
        "category": "trailhead",
        "name": "Lakeview Road Trailhead",
        "description": "Primary northern entry point with trail information board and bike racks.",
        "lat": -43.72,
        "lng": 172.28,
        "image": "https://images.unsplash.com/photo-1528490060255-bf65fc2c9fa3?auto=format&fit=crop&w=600&h=400&q=60",
        "gmaps": "https://www.google.com/maps/dir/?api=1&destination=-43.72,172.28",
        "isPublic": True,
    },
    {
        "id": "poi-birdlings-park",
        "category": "parking",
        "name": "Birdlings Flat Car Park",
        "description": "Sealed parking with space for shuttles and trailer turnarounds near the southern coast.",
        "lat": -43.85,
        "lng": 172.72,
        "image": "https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?auto=format&fit=crop&w=600&h=400&q=60",
        "gmaps": "https://www.google.com/maps/dir/?api=1&destination=-43.85,172.72",
        "isPublic": True,
    },
    {
        "id": "poi-leeston-amenities",
        "category": "amenity",
        "name": "Leeston Domain Amenities",
        "description": "Public restrooms, picnic tables, and water refill station a short detour from the trail.",
        "lat": -43.76,
        "lng": 172.30,
        "image": "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=600&h=400&q=60",
        "gmaps": "https://www.google.com/maps/dir/?api=1&destination=-43.76,172.30",
        "isPublic": True,
    },
]


def get_pois(category: str | None = None):
    items = POIS
    if category:
        items = [p for p in POIS if p["category"] == category]
    return {
        "categories": POI_CATEGORIES,
        "pois": items,
    }
